[package]
name = "mira-discord"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
chrono = { workspace = true }
mira-core = { path = "../../core" }
mira-stream-watcher = { path = "../../stream-watcher" }
uuid = { workspace = true }
